### ISSUE TITLE
Filtering for property values does not work

### ISSUE THREAD

**Issue by fabianschlebusch** [INM-6/python-odmltables#123]
When filtering for property values, the comparison 
`comparison_func(dict_prop[filter_key], filter_value)`
returns False for the filter "x==y" and two equal values because the property value is stored as a list in the odmldict.

I made a quick and dirty fix in my fork at [https://github.com/fabianschlebusch/python-odmltables](url) and will issue a pull request. However, I think that the property value should not be a list for property entries in the odmldict.

**Comment by JuliaSprenger** [comment]
Fixed via #124
