### ISSUE TITLE
PyQt5 compatibility

### ISSUE THREAD

**Issue by mdenker** [INM-6/python-odmltables#5]
The application is currently built against PyQt4, however current anaconda installations now ship with PyQt5. In these scenarios, the application will terminate with `ImportErrors`. It could be worthwhile to investigate if and how to switch to PyQt5

- [ ] version 0.2
- [x] version 1.0 (#29)

**Comment by mdenker** [comment]
A version converted to Qt5 is available at branch
https://github.com/INM-6/python-odmltables/tree/fix/qt5_port

**Comment by JuliaSprenger** [comment]
Good to know, we should fix this in the next version.

**Comment by mdenker** [comment]
Yes, but this still requires a lot of fixing. It starts now, but there are more subtle things under the hood that make it not really work yet... I think I'll downgrade to qt4 for now...

**Comment by JuliaSprenger** [comment]
see #29

**Comment by JuliaSprenger** [comment]
- [ ] version 0.2
- [x] version 1.0 (#29)

**Comment by JuliaSprenger** [comment]
#115
